language: node_js
node_js:
  - "6"
  - "node"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - TRAVIS=travis CXX=g++-4.8
